---
# handlers file for setup_docker

- name: reload docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes
  listen: "reload docker"

- name: restart docker
  service:
    name: docker
    state: restarted
  become: yes
  listen: "restart docker"

- name: docker status
  service:
    name: docker
    state: "{{docker_centos_state}}"
  when: docker_centos_state is not undefined

- name: docker en_dis
  service:
    name: docker
    enabled: "{{docker_centos_enabled}}"
  when: docker_centos_enabled is not undefined