---

- name: container mytest
  docker_container:
    name: hello-world
    image: "gookti/hello-world:hello-tomcat"
    state: started
    published_ports: 0.0.0.0:9191:8080

  register: docker_container
  tags: container

- debug: msg="{{docker_container | json_query('ansible_facts.docker_container.NetworkSettings.IPAddress')}}"
